# resume: PLACEHOLDER

# task specific
n_classes: 1
stride: 4
resized_image_size:
    - 320
    - 320
# data specific
train_ann_file: instances_train2017_person.json
val_ann_file: instances_val2017_person.json

# model specific
arch: fpn
# fpn specific
num_outs: 4
# backbone: mobilenetv4_conv_small.e2400_r224_in1k
backbone: mobilenetv4_conv_medium.e500_r256_in1k
# backbone: mobilenetv4_conv_large.e500_r256_in1k
dropout_ratio: 0
out_channel: 96
fpn_type: mm

# training specific
epochs: 24
batch_size: 128
lr: 0.000097
lr_scheduler: cosine
beta1: 0.934
beta2: 0.995
weight_decay: 0.00008

# postprocessing
min_distance: 3
threshold_abs: 0.5

# loss
loss: cfocal

# focal loss
alpha: 0.964
gamma: 2

deep_supervision: False